car/urls.py
from django.contrib import admin
from django.urls import path ,include
from .settings import *
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('frontend.urls')),
    path('api/',include('payment.urls')),
    path('api/',include('product.urls')),
    path('api/',include('purchase.urls')),
    path('api/',include('user.urls')),
    path('api/',include('advertisment.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from django import views
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static      
from django.conf import settings    
from . import views      

app_name='frontend'

urlpatterns = [          
    path('' , views.home , name='home'),    
    path('about/' , views.about ,name='about'),
    path('services/' , views.service , name='service' ),
    path('contact_us/' , views.contact_us , name='contact'),
    path('financing/' , views.financing ,name='financing'),
    path('send_financing_request/', views.send_financing_request_data, name='send_f_request_data'),
    path('FAQs & Help/' , views.FAQs , name='FAQs' ),
    path('testimonial/' , views.testimonial, name='testimonial'),
    path('team/' , views.team ,name='team'),
    path('car details/<uuid:car_id>/' , views.car_detail , name='car_details' ),
    path('contact_us/' , views.contact_us , name='contact_us'),
    path('send_contact/', views.send_contact ,name='send_contact' ),
    path('cars_inventory/' , views.cars ,name='cars'),
    path('cars-filter/', views.cars_filter_view, name='cars-filter'),
    path('log_in/' , views.log_in , name='log_in'),
    path('sign_in/' , views.sign_in , name='sign_in'), 
    path('log_out/' , views.log_out , name='log_out'),  
]

templates/cars_filter.html
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Auto Sham Cars</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Auto Sham Cars" name="keywords">
    <meta content="Auto Sham Cars" name="description">

    <!-- Auto Sham Cars Logo -->
    <link rel="preload" type="image/png" href="{% static 'img/auto_sham_logo.png'%}">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico'%}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css'%}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css'%}" rel="stylesheet">

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block">
        <div class="row">
            <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body pr-3" href=""><i class="fa fa-phone-alt mr-2"></i>+012 345 6789</a>
                    <span class="text-body">|</span>
                    <a class="text-body px-3" href=""><i class="fa fa-envelope mr-2"></i>autosham@gmail.com</a>
                </div>
            </div>
            <div class="col-md-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body px-3" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="text-body px-3" href=""><i class="fab fa-twitter"></i></a>
                    <a class="text-body px-3" href=""><i class="fab fa-linkedin-in"></i></a>
                    <a class="text-body px-3" href=""><i class="fab fa-instagram"></i></a>
                    <a class="text-body pl-3" href=""><i class="fab fa-youtube"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
    <div class="position-relative" style="z-index: 9;">
        <!-- flex-wrap:nowrap inline-style prevents wrapping across some conflicting CSS -->
        <nav class="navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 px-3" style="flex-wrap:nowrap;">
        
        <!-- Brand / Logo (flex-shrink-0 to avoid it stealing width) -->
        <a href="home.html" class="navbar-brand d-flex align-items-center flex-shrink-0 mr-2" style="padding-right:0;">
            <img src="{% static 'img/auto_sham_logo.png'%}"
                alt="auto sham car logo"
                class="img-fluid d-inline-block align-top"
                style="max-height:120px; max-width:500px; width:auto; height:auto;">
        </a>

        <!-- Navbar toggler (keeps toggler immediately after brand) -->
        <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible Menu -->
        <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
            <ul class="navbar-nav ml-auto py-0">
            <li class="nav-item"><a href="{% url 'frontend:home'%}" class="nav-link"><i class="fa fa-home mr-1"></i> Home</a></li>
            <li class="nav-item"><a href="{% url 'frontend:about'%}" class="nav-link"><i class="fa fa-info-circle mr-2"></i>About</a></li>
            <li class="nav-item"><a href="{% url 'frontend:service'%}" class="nav-link"><i class="fa fa-cogs mr-2"></i>Service</a></li>

            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-car mr-2"></i>Cars</a>
                <div class="dropdown-menu rounded-0 m-0">
                <a href="{% url 'frontend:cars'%}" class="dropdown-item"><i class="fa fa-list mr-2"></i>Car Inventory</a>
                <a href="{% url 'frontend:financing'%}" class="dropdown-item"><i class="fa fa-credit-card mr-2"></i>Financing</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-alt mr-2"></i>Pages</a>
                <div class="dropdown-menu rounded-0 m-0">
                <a href="{% url 'frontend:team'%}" class="dropdown-item"><i class="fa fa-users mr-2"></i>The Team</a>
                <a href="{% url 'frontend:testimonial'%}" class="dropdown-item"><i class="fa fa-comment-dots mr-2"></i>Testimonial</a>
                <a href="{% url 'frontend:FAQs'%}" class="dropdown-item"><i class="fa fa-question-circle mr-2"></i>FAQs & Help</a>
                </div>
            </li>

            <li class="nav-item"><a href="{% url 'frontend:contact'%}" class="nav-link"><i class="fa fa-envelope mr-2"></i>Contact</a></li>
            </ul>
        </div>

        </nav>
    </div>
    </div>
    <!-- Navbar End -->

    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <h1 class="display-4 text-uppercase text-center mb-5">Find Your Car</h1>
            <div class="row">
                {% for car in cars %}
                <div class="col-lg-4 col-md-6 mb-2">
                    <div class="rent-item active mb-4" style="padding: 0%;">
                        {% if car.img %}
                            <img class="img-fluid mb-4" src="{{ car.img.url }}" alt="">
                        {% else %}
                            <img class="img-fluid mb-4" src="/static/img/no-car.png" alt="">
                        {% endif %}
                        
                        <h4 class="text-uppercase mb-4">{{ car.carModel.manufacturer.name }} {{ car.carModel.name }}</h4>
                        <div class="d-flex justify-content-center mb-4">
                            <div class="px-2">
                                <i class="fa fa-car text-primary mr-1"></i>
                                <span>{{ car.carModel.model_date }}</span>
                            </div>
                            <div class="px-2 border-left border-right">
                                <i class="fa fa-cogs text-primary mr-1"></i>
                                <span>AUTO</span>
                            </div>
                            <div class="px-2">
                                <i class="fa fa-road text-primary mr-1"></i>
                                <span>{{ car.current_kilometer }}</span>
                            </div>
                        </div>
                        <a class="btn btn-primary px-3 mb-4" href="{% url 'frontend:car_details' car_id=car.id %}">Car Details</a>
                    </div>
                </div>
            {% empty %}
                <p class="text-center">No cars found.</p>
            {% endfor %}
            </div>      
        </div>
    </div>


    <!-- Vendor Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="owl-carousel vendor-carousel">
                <div class="p-3 mx-2"><img src="{% static 'logos/rolls_royce.png'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/bmw.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/dodge.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/lamborghini.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/ford.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/kia.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/lexus.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/mercedes.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/tesla.png'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/porsche.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/honda.svg'%}" alt="" width="30%" height="30%"></div>
                <div class="p-3 mx-2"><img src="{% static 'logos/nissan.svg'%}" alt="" width="30%" height="30%"></div>
            </div>
        </div>
    </div>
    <!-- Vendor End -->

    <!-- Footer Start -->
    <div class="container-fluid bg-secondary py-5 px-sm-3 px-md-5" style="margin-top: 90px;">
        <div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <img src="{% static 'img/auto_sham_logo.png'%}" alt="auto sham cars logo" width="100%" height="80%">
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-uppercase text-light mb-4">Business Hours</h4>
                <p class="mb-4">We’re here to serve you every day between 10 AM and 10 PM, making it easy to visit us when it suits your schedule</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-uppercase text-light mb-4">Usefull Links</h4>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-body mb-2" href="{% url 'frontend:cars'%}"><i class="fa fa-angle-right text-white mr-2"></i>Cars Inventory</a>
                    <a class="text-body mb-2" href="{% url 'frontend:financing'%}"><i class="fa fa-angle-right text-white mr-2"></i>Financing</a>
                    <a class="text-body mb-2" href="{% url 'frontend:contact'%}"><i class="fa fa-angle-right text-white mr-2"></i>Contact us</a>
                    <a class="text-body" href="{% url 'frontend:FAQs'%}"><i class="fa fa-angle-right text-white mr-2"></i>Help & FAQs</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-uppercase text-light mb-4">Get In Touch</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-white mr-3"></i>123 Street, Damascus</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-white mr-3"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope text-white mr-3"></i>autosham@gmail.com.com</p>
                <h6 class="text-uppercase text-white py-2">Follow Us</h6>
                <div class="d-flex justify-content-start">
                    <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-lg btn-dark btn-lg-square" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js'%}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js'%}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js'%}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js'%}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js'%}"></script>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js'%}"></script>
    <!-- Template Javascript -->
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

{% endblock %}

templates/log_in.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Log In - Auto Sham</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body { 
            background: linear-gradient(rgba(28, 30, 50, .9), rgba(28, 30, 50, .9)), url("{% static 'img/bg-banner.jpg'%}");
            background-repeat: no-repeat;
            background-size: cover;
        }
        .card-register 
        { 
            max-width: 500px;
            margin-top: 80px;
            margin-bottom: 200px;
            margin-left: auto;
            margin-right: auto; 
            padding: 30px; 
            border-radius: 20px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2); 
            background: white; }
        .card-register h3 { 
            margin-bottom: 20px; 
        }
    </style>
</head>
<body>
<div class="card card-register">
    <h3 class="text-center">Log in To Your Account</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="mb-3">
            {{ form.password.label_tag }}
            {{ form.password }}
            {{ form.password.errors }}
        </div>
        <button type="submit" class="btn btn-primary w-100" style="border-radius: 20px;">Log in</button>
    </form>
    <p class="text-center mt-3">
          Don't have an account?
        <a href="{% url 'frontend:sign_in'%}">Register here</a>
    </p>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock%}

templates/sign_in.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up - Auto Sham</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body { 
            background: linear-gradient(rgba(28, 30, 50, .9), rgba(28, 30, 50, .9)), url("{% static 'img/bg-banner.jpg'%}");
            background-repeat: no-repeat;
            background-size: cover;
        }
        .card-register { max-width: 500px; margin: 80px auto; padding: 30px; border-radius: 20px; box-shadow: 0 0 15px rgba(0,0,0,0.2); background: white; }
        .card-register h3 { margin-bottom: 20px; }
    </style>
</head>
<body>
<div class="card card-register">
    <h3 class="text-center">Create Account</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="mb-3">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="mb-3">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="mb-3">
            {{ form.country.label_tag }}
            {{ form.country }}
            {{ form.country.errors }}
        </div>
        <div class="mb-3">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {{ form.password1.errors }}
        </div>
        <div class="mb-3">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {{ form.password2.errors }}
        </div>
        <div class="mb-3">
            {{ form.birthdate.label_tag }}
            {{ form.birthdate }}
            {{ form.birthdate.errors }}
        </div>
        <div class="mb-3">
            {{ form.address.label_tag }}
            {{ form.address }}
            {{ form.address.errors }}
        </div>
        <div class="form-check mb-3">
            {{ form.is_maried }} {{ form.is_maried.label_tag }}
        </div>
        <button type="submit" class="btn btn-primary w-100" style="border-radius: 20px;">Register</button>
    </form>
    <p class="text-center mt-3">
          Already have an account?
        <a href="{% url 'frontend:log_in'%}">Log in here</a>
    </p>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock%}